import { LiveChannel, VodMovie, SeriesItem, XtreamCategory, SeriesDetails, VodDetails } from '../types';

export const MOCK_CATEGORIES = {
  live: [
    { category_id: 'all', category_name: 'All Channels' },
    { category_id: 'live_news', category_name: 'News & Information' },
    { category_id: 'live_sports', category_name: 'Sports & Action 4K' },
    { category_id: 'live_cinema', category_name: 'Cinema & Entertainment' },
    { category_id: 'live_doc', category_name: 'Documentary & Nature 4K' },
    { category_id: 'live_music', category_name: 'Music & Concerts' },
  ],
  vod: [
    { category_id: 'all', category_name: 'All Movies' },
    { category_id: 'vod_4k', category_name: '4K Ultra HD Cinema' },
    { category_id: 'vod_action', category_name: 'Sci-Fi & Action' },
    { category_id: 'vod_animation', category_name: 'Animation & CGI' },
    { category_id: 'vod_drama', category_name: 'Drama & Thriller' },
    { category_id: 'vod_fantasy', category_name: 'Fantasy & Adventure' },
  ],
  series: [
    { category_id: 'all', category_name: 'All Series' },
    { category_id: 'ser_scifi', category_name: 'Sci-Fi Chronicles 4K' },
    { category_id: 'ser_action', category_name: 'Action & Mystery' },
    { category_id: 'ser_doc', category_name: 'Nature & Space Series' },
    { category_id: 'ser_anim', category_name: 'Animated Sagas' },
  ],
};

export const MOCK_LIVE_CHANNELS: LiveChannel[] = [
  {
    num: 1,
    name: 'NASA TV UHD - Live Earth & ISS Stream',
    stream_id: 101,
    stream_icon: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&auto=format&fit=crop&q=80',
    category_id: 'live_doc',
    direct_source: 'https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8',
    is4k: true,
  },
  {
    num: 2,
    name: 'Red Bull Extreme Sports HD',
    stream_id: 102,
    stream_icon: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=400&auto=format&fit=crop&q=80',
    category_id: 'live_sports',
    direct_source: 'https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8',
    is4k: true,
  },
  {
    num: 3,
    name: 'Global News Wire HD - Live Feed',
    stream_id: 103,
    stream_icon: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=400&auto=format&fit=crop&q=80',
    category_id: 'live_news',
    direct_source: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    is4k: false,
  },
  {
    num: 4,
    name: 'Cinema World 4K - Open Broadcast',
    stream_id: 104,
    stream_icon: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&auto=format&fit=crop&q=80',
    category_id: 'live_cinema',
    direct_source: 'https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8',
    is4k: true,
  },
  {
    num: 5,
    name: 'Horizon Live 4K UHD Feed',
    stream_id: 105,
    stream_icon: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=400&auto=format&fit=crop&q=80',
    category_id: 'live_news',
    direct_source: 'https://test-streams.mux.dev/test_001/stream.m3u8',
    is4k: false,
  },
  {
    num: 6,
    name: 'Blender 24/7 Animation Showcase 4K',
    stream_id: 106,
    stream_icon: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&auto=format&fit=crop&q=80',
    category_id: 'live_cinema',
    direct_source: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    is4k: true,
  },
];

export const MOCK_MOVIES: VodMovie[] = [
  {
    num: 1,
    name: 'Tears of Steel (4K Ultra HD)',
    stream_id: 201,
    stream_icon: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    rating: 8.4,
    rating_5based: 4.2,
    category_id: 'vod_4k',
    year: '2023',
    container_extension: 'mp4',
    is4k: true,
  },
  {
    num: 2,
    name: 'Cosmos Laundromat - First Cycle (4K)',
    stream_id: 202,
    stream_icon: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    rating: 8.8,
    rating_5based: 4.4,
    category_id: 'vod_4k',
    year: '2024',
    container_extension: 'mp4',
    is4k: true,
  },
  {
    num: 3,
    name: 'Big Buck Bunny (Remastered 60FPS)',
    stream_id: 203,
    stream_icon: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    rating: 8.1,
    rating_5based: 4.05,
    category_id: 'vod_animation',
    year: '2022',
    container_extension: 'mp4',
    is4k: true,
  },
  {
    num: 4,
    name: 'Sintel: The Dragon Quest',
    stream_id: 204,
    stream_icon: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?w=600&auto=format&fit=crop&q=80',
    rating: 8.6,
    rating_5based: 4.3,
    category_id: 'vod_fantasy',
    year: '2023',
    container_extension: 'mp4',
    is4k: true,
  },
  {
    num: 5,
    name: 'Elephants Dream: Neural Matrix',
    stream_id: 205,
    stream_icon: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    rating: 7.9,
    rating_5based: 3.95,
    category_id: 'vod_action',
    year: '2021',
    container_extension: 'mp4',
    is4k: false,
  },
  {
    num: 6,
    name: 'Cyberpunk Metropolis: Neon Horizon',
    stream_id: 206,
    stream_icon: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&auto=format&fit=crop&q=80',
    rating: 8.9,
    rating_5based: 4.45,
    category_id: 'vod_action',
    year: '2024',
    container_extension: 'mp4',
    is4k: true,
  },
];

export const MOCK_SERIES: SeriesItem[] = [
  {
    num: 1,
    name: 'Chronicles of the Void (4K HDR)',
    series_id: 301,
    cover: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=600&auto=format&fit=crop&q=80',
    plot: 'In a dystopian future setting, a group of scientists and rogue pilots uncover an ancient cosmic rift threatening the inner colonies of Mars.',
    cast: 'Derek de Lint, Sergio Hasselbaink, Vanja Rukavina',
    director: 'Ian Hubert',
    genre: 'Sci-Fi / Space Opera / Mystery',
    releaseDate: '2024',
    rating: 9.1,
    category_id: 'ser_scifi',
    is4k: true,
  },
  {
    num: 2,
    name: 'Project Gooseberry: Infinite Odyssey',
    series_id: 302,
    cover: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    plot: 'A depressed sheep named Franck faces his fears across bizarre alternate dimensions guided by a charismatic cosmic sales agent named Victor.',
    cast: 'Pierre Bokma, Reinout Scholten van Aschat',
    director: 'Mathieu Auvray',
    genre: 'Surreal / Adventure / Animation',
    releaseDate: '2023',
    rating: 8.7,
    category_id: 'ser_anim',
    is4k: true,
  },
  {
    num: 3,
    name: 'Apex Predator: Earth Unveiled 4K',
    series_id: 303,
    cover: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=600&auto=format&fit=crop&q=80',
    plot: 'State-of-the-art camera technology reveals the secretive lives of the oceans, deep trenches, and frozen tundras in stunning 4K 60FPS.',
    cast: 'Narrated by Sir David Reynolds',
    director: 'Elena Rostova',
    genre: 'Documentary / Nature / Science',
    releaseDate: '2024',
    rating: 9.4,
    category_id: 'ser_doc',
    is4k: true,
  },
];

export const MOCK_MOVIE_DETAILS: Record<number, VodDetails> = {
  201: {
    info: {
      name: 'Tears of Steel (4K Ultra HD)',
      movie_image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&auto=format&fit=crop&q=80',
      plot: 'Set in a dystopian future Amsterdam, a squad of rebel soldiers and robotics engineers attempt to reconstruct an old memory to save humanity from impending autonomous drone swarms.',
      cast: 'Derek de Lint, Sergio Hasselbaink, Vanja Rukavina, Denise Rebergen',
      director: 'Ian Hubert',
      genre: 'Sci-Fi, Cyberpunk, Action',
      releaseDate: '2023-04-12',
      duration_secs: 734,
      duration: '12m 14s',
      rating: 8.4,
      backdrop_path: [
        'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
      ],
      video: { width: 3840, height: 2160, codec: 'HEVC / H.265' },
      audio: { codec: 'Dolby Digital Plus 5.1', channels: 6 },
      bitrate: 18500000,
    },
    movie_data: {
      stream_id: 201,
      name: 'Tears of Steel',
      container_extension: 'mp4',
    },
  },
  202: {
    info: {
      name: 'Cosmos Laundromat - First Cycle (4K)',
      movie_image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
      plot: 'On a desolate windswept island, a suicidal sheep meets a mysterious stranger who offers him the adventure of a lifetime across endless parallel universes.',
      cast: 'Pierre Bokma, Reinout Scholten van Aschat',
      director: 'Mathieu Auvray',
      genre: 'Animation, Dark Fantasy, Sci-Fi',
      releaseDate: '2024-01-20',
      duration_secs: 720,
      duration: '12m 00s',
      rating: 8.8,
      backdrop_path: [
        'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=1600&auto=format&fit=crop&q=80',
      ],
      video: { width: 3840, height: 2160, codec: 'HEVC 4K UHD' },
      audio: { codec: 'AC3 Stereo', channels: 2 },
      bitrate: 22000000,
    },
    movie_data: {
      stream_id: 202,
      name: 'Cosmos Laundromat',
      container_extension: 'mp4',
    },
  },
  203: {
    info: {
      name: 'Big Buck Bunny (Remastered 60FPS)',
      movie_image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80',
      plot: 'A large, lovable bunny wakes up on a sunny forest morning only to be harassed by a mischievous trio of woodland bullies. When they cross the line, Bunny engineers an ingenious, hilarious trap.',
      cast: 'Animated Classic Characters',
      director: 'Sacha Goedegebure',
      genre: 'Animation, Comedy, Family',
      releaseDate: '2022-08-15',
      duration_secs: 596,
      duration: '9m 56s',
      rating: 8.1,
      backdrop_path: [
        'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
      ],
      video: { width: 1920, height: 1080, codec: 'H.264 High@L4.2' },
      audio: { codec: 'AAC 5.1 Surround', channels: 6 },
      bitrate: 12000000,
    },
    movie_data: {
      stream_id: 203,
      name: 'Big Buck Bunny',
      container_extension: 'mp4',
    },
  },
  204: {
    info: {
      name: 'Sintel: The Dragon Quest',
      movie_image: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?w=1200&auto=format&fit=crop&q=80',
      plot: 'A lonely young warrior girl named Sintel nurses a wounded dragon baby back to health. When the creature is kidnapped by an adult beast, Sintel embarks on an arduous quest across frozen wastes.',
      cast: 'Halina Reijn, Thom Hoffman',
      director: 'Colin Levy',
      genre: 'Fantasy, Drama, Adventure',
      releaseDate: '2023-11-05',
      duration_secs: 888,
      duration: '14m 48s',
      rating: 8.6,
      backdrop_path: [
        'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1600&auto=format&fit=crop&q=80',
      ],
      video: { width: 3840, height: 2160, codec: 'HEVC / H.265' },
      audio: { codec: 'DTS 5.1 Surround', channels: 6 },
      bitrate: 24000000,
    },
    movie_data: {
      stream_id: 204,
      name: 'Sintel',
      container_extension: 'mp4',
    },
  },
  205: {
    info: {
      name: 'Elephants Dream: Neural Matrix',
      movie_image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80',
      plot: 'Proog and Emo traverse a gigantic, ever-shifting mechanical labyrinth that reacts to human thought and subconscious dread in surreal and unpredictable ways.',
      cast: 'Tygo Gernandt, Cas Jansen',
      director: 'Bassam Kurdali',
      genre: 'Sci-Fi, Surrealism, Mystery',
      releaseDate: '2023-09-14',
      duration_secs: 654,
      duration: '10m 54s',
      rating: 7.9,
      backdrop_path: [
        'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
      ],
      video: { width: 1920, height: 1080, codec: 'H.264 High' },
      audio: { codec: 'AC3 5.1 Surround', channels: 6 },
      bitrate: 15000000,
    },
    movie_data: {
      stream_id: 205,
      name: 'Elephants Dream',
      container_extension: 'mp4',
    },
  },
  206: {
    info: {
      name: 'Cyberpunk Metropolis: Neon Horizon',
      movie_image: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1200&auto=format&fit=crop&q=80',
      plot: 'A high-octane visual journey into a megacity illuminated by neon billboards, flying vehicles, and synthetic digital consciousness.',
      cast: 'Visual Showcase Ensemble',
      director: 'Elena Rostova',
      genre: 'Cyberpunk, Sci-Fi, Ambient',
      releaseDate: '2024-03-01',
      duration_secs: 742,
      duration: '12m 22s',
      rating: 8.9,
      backdrop_path: [
        'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1600&auto=format&fit=crop&q=80',
      ],
      video: { width: 3840, height: 2160, codec: 'HEVC 4K' },
      audio: { codec: 'Dolby Atmos', channels: 8 },
      bitrate: 28000000,
    },
    movie_data: {
      stream_id: 206,
      name: 'Cyberpunk Metropolis',
      container_extension: 'mp4',
    },
  },
};

export const MOCK_SERIES_DETAILS: Record<number, SeriesDetails> = {
  301: {
    info: {
      name: 'Chronicles of the Void (4K HDR)',
      cover: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=1200&auto=format&fit=crop&q=80',
      plot: 'In a dystopian future setting, a group of scientists and rogue pilots uncover an ancient cosmic rift threatening the inner colonies of Mars. As temporal anomalies rip through the solar system, only a cybernetically enhanced navigator can chart a path through the storm.',
      cast: 'Derek de Lint, Sergio Hasselbaink, Vanja Rukavina, Denise Rebergen',
      director: 'Ian Hubert',
      genre: 'Sci-Fi / Space Opera / Mystery',
      releaseDate: '2024',
      rating: 9.1,
      episode_run_time: '12-15 min',
      backdrop_path: [
        'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80',
      ],
    },
    seasons: [
      { season_number: 1, name: 'Season 1: Amsterdam Genesis', episode_count: 3 },
      { season_number: 2, name: 'Season 2: Deep Horizon', episode_count: 2 },
    ],
    episodes: {
      '1': [
        {
          id: 30101,
          season: 1,
          episode_num: 1,
          title: 'Episode 1: The Amsterdam Anomaly',
          container_extension: 'mp4',
          info: {
            duration_secs: 734,
            duration: '12m 14s',
            plot: 'In the heart of the ruins of Amsterdam, Celia leads an extraction team to capture a live memory core before autonomous sentinel drones obliterate the sector.',
            movie_image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
            rating: 9.0,
            release_date: '2024-01-10',
          },
        },
        {
          id: 30102,
          season: 1,
          episode_num: 2,
          title: 'Episode 2: The Neural Bridge',
          container_extension: 'mp4',
          info: {
            duration_secs: 720,
            duration: '12m 00s',
            plot: 'Thom syncs his cybernetic implants with the recovered alien transmission, triggering vivid flashbacks that blur the lines between past and simulation.',
            movie_image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
            rating: 9.2,
            release_date: '2024-01-17',
          },
        },
        {
          id: 30103,
          season: 1,
          episode_num: 3,
          title: 'Episode 3: Iron & Starlight',
          container_extension: 'mp4',
          info: {
            duration_secs: 888,
            duration: '14m 48s',
            plot: 'The final confrontation at the central spaceport forces the rebel squad to make the ultimate sacrifice to transmit the coordinates to Mars orbit.',
            movie_image: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?w=600&auto=format&fit=crop&q=80',
            rating: 9.4,
            release_date: '2024-01-24',
          },
        },
      ],
      '2': [
        {
          id: 30104,
          season: 2,
          episode_num: 1,
          title: 'Episode 1: The Martian Quarantine',
          container_extension: 'mp4',
          info: {
            duration_secs: 600,
            duration: '10m 00s',
            plot: 'Orbiting the red planet, the survivors discover that the colony has already been subverted by the self-replicating biomechanical threat.',
            movie_image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
            rating: 8.9,
            release_date: '2024-08-01',
          },
        },
        {
          id: 30105,
          season: 2,
          episode_num: 2,
          title: 'Episode 2: Core Overdrive (Finale)',
          container_extension: 'mp4',
          info: {
            duration_secs: 780,
            duration: '13m 00s',
            plot: 'The dreadnought initiates slipstream drive directly inside the atmosphere, triggering a chain reaction across the martian canyons.',
            movie_image: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&auto=format&fit=crop&q=80',
            rating: 9.5,
            release_date: '2024-08-08',
          },
        },
      ],
    },
  },
  302: {
    info: {
      name: 'Project Gooseberry: Infinite Odyssey',
      cover: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
      plot: 'A surreal journey across dimensions where reality fractures and rebuilds at every warp gate.',
      cast: 'Pierre Bokma, Reinout Scholten van Aschat',
      director: 'Mathieu Auvray',
      genre: 'Surreal / Adventure / Animation',
      releaseDate: '2023',
      rating: 8.7,
      episode_run_time: '12 min',
      backdrop_path: [
        'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=1600&auto=format&fit=crop&q=80',
      ],
    },
    seasons: [
      { season_number: 1, name: 'Season 1: Fractured Horizons', episode_count: 2 },
    ],
    episodes: {
      '1': [
        {
          id: 30201,
          season: 1,
          episode_num: 1,
          title: 'Episode 1: The Island of Shadows',
          container_extension: 'mp4',
          info: {
            duration_secs: 720,
            duration: '12m 00s',
            plot: 'Franck awakens in an endless stormy expanse where clocks tick backwards.',
            movie_image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
            rating: 8.7,
            release_date: '2023-05-12',
          },
        },
        {
          id: 30202,
          season: 1,
          episode_num: 2,
          title: 'Episode 2: The Cosmic Laundromat',
          container_extension: 'mp4',
          info: {
            duration_secs: 740,
            duration: '12m 20s',
            plot: 'Victor shows Franck the infinite machine that cleanses universes.',
            movie_image: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=600&auto=format&fit=crop&q=80',
            rating: 8.9,
            release_date: '2023-05-19',
          },
        },
      ],
    },
  },
  303: {
    info: {
      name: 'Apex Predator: Earth Unveiled 4K',
      cover: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200&auto=format&fit=crop&q=80',
      plot: 'Pristine 4K footage documenting wild nature across oceanic trenches and volcanic peaks.',
      cast: 'Narrated by Sir David Reynolds',
      director: 'Elena Rostova',
      genre: 'Documentary / Nature / Science',
      releaseDate: '2024',
      rating: 9.4,
      episode_run_time: '15 min',
      backdrop_path: [
        'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
      ],
    },
    seasons: [
      { season_number: 1, name: 'Season 1: Deep Wilds', episode_count: 2 },
    ],
    episodes: {
      '1': [
        {
          id: 30301,
          season: 1,
          episode_num: 1,
          title: 'Episode 1: Secrets of the Coral Trenches',
          container_extension: 'mp4',
          info: {
            duration_secs: 800,
            duration: '13m 20s',
            plot: 'Submersibles descend into the abyss uncovering bioluminescent wonders.',
            movie_image: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=600&auto=format&fit=crop&q=80',
            rating: 9.4,
            release_date: '2024-02-10',
          },
        },
        {
          id: 30302,
          season: 1,
          episode_num: 2,
          title: 'Episode 2: The Arctic Migrations',
          container_extension: 'mp4',
          info: {
            duration_secs: 840,
            duration: '14m 00s',
            plot: 'Aerial drones track predators across vast shifting polar pack ice.',
            movie_image: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=600&auto=format&fit=crop&q=80',
            rating: 9.5,
            release_date: '2024-02-17',
          },
        },
      ],
    },
  },
};

// Reliable public playable streaming URLs for demo playback
export const SAMPLE_STREAM_URLS: Record<number, string> = {
  // Live Channels (HLS adaptive streams - verified 200 OK with CORS)
  101: 'https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8',
  102: 'https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8',
  103: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  104: 'https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8',
  105: 'https://test-streams.mux.dev/test_001/stream.m3u8',
  106: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',

  // Movies (HLS / MP4 adaptive multi-bitrate streams - verified 200 OK with CORS)
  201: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
  202: 'https://vjs.zencdn.net/v/oceans.mp4',
  203: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  204: 'https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8',
  205: 'https://test-streams.mux.dev/test_001/stream.m3u8',
  206: 'https://vjs.zencdn.net/v/oceans.mp4',

  // Series Episodes (verified 200 OK with CORS)
  30101: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
  30102: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  30103: 'https://vjs.zencdn.net/v/oceans.mp4',
  30104: 'https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8',
  30105: 'https://test-streams.mux.dev/test_001/stream.m3u8',
  30201: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
  30202: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  30203: 'https://vjs.zencdn.net/v/oceans.mp4',
  30301: 'https://vjs.zencdn.net/v/oceans.mp4',
  30302: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
};
